spring:
  application:
    name: bugpingGateway
  cloud:
    gateway:
      routes:
        - id: ms2
          uri: http://localhost:8708/
          predicates:
          - Path=/notice/**
        - id: ms1
          uri: http://localhost:8707/
          predicates:
          - Path=/**
  eureka:
    client:
      register-with-eureka: 'true'
      fetch-registry: 'true'
      service-url:
        defaultZone: http://localhost:8761/eureka
server:
  port: 7777