spring:
  application:
    name: bugpingDiscovery

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false # Eureka 서버 자신은 다른 Eureka 서버에 등록하지 않음
    fetch-registry: false # 자신의 레지스트리를 가져올 필요 없음